[tools]
aws = { version = "2.33.17", symlink_bins = "true" }
bun = "1.3.8"
claude = "2.1.37"
codex = "0.98.0"
duckdb = "1.4.4"
gh = "2.86.0"
jq = "1.8.1"
node = "24.13.0"
pnpm = "10.29.1"
postgres = "18.1"
pre-commit = "4.5.1"
ripgrep = "15.1.0"
terraform = "1.14.4"
trivy = "0.69.1"
